[phases.setup]
nixPkgs = [
  "php82",
  "php82Extensions.pdo",
  "php82Extensions.pdo_pgsql",
  "php82Extensions.pgsql",
  "php82Extensions.mbstring",
  "php82Extensions.openssl"
]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]
